[package]
name = "test-async"
version = "0.1.0"
authors = ["Tomas Chabada <tchabada@gmail.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "=0.3.0-alpha.19", default-features = false, features = ["alloc"]}
tokio = "=0.2.0-alpha.6"
tokio-postgres = { version = "=0.5.0-alpha.1", features = ["with-chrono-0_4"] }
tonic = { version = "0.1.0-alpha.4", features = ["rustls"] }
async-stream = "0.2.0"
bytes = "0.4.12"
prost = "0.5.0"
prost-derive = "0.5"
prost-types = "0.5.0"
http = "0.1.19"
tower = "=0.3.0-alpha.2"
serde = "1.0.102"
serde_json = "1.0.41"
serde_derive = "1.0.102"
console = "0.9.1"
dotenv = "0.15.0"
chrono = "0.4.9"
uuid = { version = "0.8.1", features = ["serde", "v4"] }

[build-dependencies]
tonic-build = "0.1.0-alpha.4"
